#!/usr/bin/env bash
#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  
#  ╠╩╗╚═╗╠═╝║║║║║║  
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 2 3 4 5 6 7 8 9

bspc config border_width        2
bspc config window_gap          5
bspc config top_padding         35

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a krita state=fullscreen border=off


xset b off

#export _JAVA_AWT_WM_NONREPARENTING=1 # p/ fazer o intellij, etc do java funfar


xrandr --output HDMI-1 --mode 1384x900_60.00

 # background img
feh --bg-scale /home/matheus/Imagens/A1/0002.5/escolhidos_rice_1/kill_la_kill_07.jpg 
# xgifwallpaper /home/matheus/Downloads/walpape.gif # wallpaper animeado

picom &

/home/matheus/.config/bspwm/rice/themes/ryoko/launch.sh
